# Generated by Django 2.1.5 on 2019-12-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20191222_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='m', max_length=8),
        ),
    ]
