# Generated by Django 2.1.5 on 2019-12-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesetting',
            name='id',
        ),
        migrations.RemoveField(
            model_name='storesetting',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='storesetting',
            name='price_multiplier',
        ),
        migrations.AddField(
            model_name='storesetting',
            name='name',
            field=models.CharField(default='unused', max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='value',
            field=models.TextField(default=''),
        ),
    ]
