# Generated by Django 2.1.5 on 2019-12-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartthrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, through='store.Cartthrough', to='store.Product'),
        ),
        migrations.AddField(
            model_name='cartthrough',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Customer'),
        ),
        migrations.AddField(
            model_name='cartthrough',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
